"use strict";
exports.__esModule = true;
var express_1 = require("express");
var userRouter_1 = require("./userRouter");
var productRouter_1 = require("./productRouter");
var storeRouter_1 = require("./storeRouter");
var adminRouter_1 = require("./adminRouter");
var categoryRouter_1 = require("./categoryRouter");
var staffRouter_1 = require("./staffRouter");
var sellerRouter_1 = require("./sellerRouter");
var logeddInRouter_1 = require("./logeddInRouter");
var router = (0, express_1.Router)();
router.use('/', userRouter_1.userRouter);
router.use('/admin', adminRouter_1.adminRouter);
router.use('/staff', staffRouter_1.staffRouter);
router.use('/seller', sellerRouter_1.sellerRouter);
router.use('/products', productRouter_1.productRouter);
router.use('/store', storeRouter_1.storeRouter);
router.use('/categories', categoryRouter_1["default"]);
router.use('/account', logeddInRouter_1.loggedInRouter);
exports["default"] = router;
